[project]
name = "omega-dao"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.omega_dao]
path = "contracts/omega_dao.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
